### ISSUE TITLE
Which JetPack and TF Version?

### ISSUE THREAD

**Issue by DennisFaucher** [dataplayer12/homesecurity#13]
Hi. Great project. As I work through errors running on Nano withJetPack 4.3, I am finding that your project requires tensorflow<2 and CUDA=10.0. Is that correct? Which JetPack version and TF version did you use successfully with your project? TIA.

**Comment by dataplayer12** [comment]
Hi Dennis, Yes tf <2 is required. The CUDA version is not that important as long as tensorflow can use the gpu on your nano. In terms of JetPack, someone has recently tested it with 4.4 and I have pushed out some commits to make everything work with the latest version of JetPack, so I think you should not have too many problems getting it to work on either 4.3 or 4.4. If you encounter problems or bugs, let me know.

**Comment by DennisFaucher** [comment]
OK. Rebuilt Nano from scratch. launch.sh coredumps. I htink CUDA 10.0 rather than 10.2 is needed. Here is what I did to rebuild the Nano:

Re-flashed JetPack v4.3
$ sudo apt-get update
$ sudo apt-get install libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev liblapack-dev libblas-dev gfortran
$ sudo apt-get install python3-pip
$ sudo pip3 install -U pip testresources setuptools
$ sudo pip3 install -U numpy==1.16.1 future==0.18.2 mock==3.0.5 h5py==2.10.0 keras_preprocessing==1.1.1 keras_applications==1.0.8 gast==0.2.2 futures protobuf pybind11
$ sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 “tensorflow<2”
$ cd ./homesecurity
$ vi confidential.txt
{"recepients": ["dennis@faucher.net"], "myemail": "dennisfaucher@gmail.com", "mypass": "NotMyPassword"}
$ vi launch.sh
#DEVICE="jetsontx2"
DEVICE="jetsonano"
$ bash launch.sh
Setting up h264 directory
Setting up MP4 directory
2020-09-10 00:44:06.477047: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/python3.6/dist-packages/cv2/../../../../lib/aarch64-linux-gnu:
2020-09-10 00:44:06.477111: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-10 00:44:06.477373: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/python3.6/dist-packages/cv2/../../../../lib/aarch64-linux-gnu:
2020-09-10 00:44:06.477442: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
launch.sh: line 44:  5443 Segmentation fault      (core dumped) python3 jetsonano/securitycamnano.py
$ sudo find / -name libcudart*
/usr/local/cuda-10.2/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.2/doc/man/man7/libcudart.7
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcudart_static.a
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcudart.so.10.2.89
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcudart.so
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcudart.so.10.2

**Comment by DennisFaucher** [comment]
Next idea: Flash JetPack which includes tensorflow v1

Did that. No tf errors. Yay. I think I need to run the dusty script to install the models though. Here's the launch.sh error:

$ bash launch.sh
Traceback (most recent call last):
  File "jetsonano/securitycamnano.py", line 11, in <module>
    from file_managernano import FileManagerThread, FileCleanerThread, counter
  File "/home/jetson/homesecurity/jetsonano/file_managernano.py", line 6, in <module>
    import human_detect as hd
  File "/home/jetson/homesecurity/human_detection/human_detect.py", line 63, in <module>
    odapi = DetectorAPI(path_to_ckpt=model_path)
  File "/home/jetson/homesecurity/human_detection/human_detect.py", line 19, in __init__
    serialized_graph = fid.read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb; No such file or directory

**Comment by DennisFaucher** [comment]
OK, found the issue with the model not found. I need to change /home/jetson/homesecurity/human_detection/human_detect.py", line 63 to include the full path to the model. Now launch.sh starts.
#model_path = 'ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb'
model_path = '/home/jetson/homesecurity/human_detection/ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb'

**Comment by dataplayer12** [comment]
Sorry for being late in response. Yes, sometimes python needs the full path to your model file. I will make the path relative to avoid more confusion.
