### ISSUE TITLE
Change from person detection to car detection

### ISSUE THREAD

**Issue by DennisFaucher** [dataplayer12/homesecurity#15]
Would changing line 33 of human_detect.py from detection_classes:0 to detection_classes:2 detect cars instead of people? Thank you.

COCO Classes
1 | person | person | person | person
2 | bicycle | bicycle | bicycle | vehicle
3 | car | car | car | vehicle

**Comment by dataplayer12** [comment]
Yes, it would and it would send you an email every time a car was detected.

**Comment by DennisFaucher** [comment]
Beautiful. That's my use case. I'll try that and then see if I can make the camera my RTSP IP camera.

**Comment by DennisFaucher** [comment]
Class must be specified somewhere else.

I changed 
        self.detection_classes = self.detection_graph.get_tensor_by_name('detection_classes:0')
to
        self.detection_classes = self.detection_graph.get_tensor_by_name('detection_classes:2')

and received this error

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jetsonano/securitycamnano.py", line 11, in <module>
    from file_managernano import FileManagerThread, FileCleanerThread, counter
  File "/home/jetson/homesecurity/jetsonano/file_managernano.py", line 6, in <module>
    import human_detect as hd
  File "/home/jetson/homesecurity/human_detection/human_detect.py", line 65, in <module>
    odapi = DetectorAPI(path_to_ckpt=model_path)
  File "/home/jetson/homesecurity/human_detection/human_detect.py", line 34, in __init__
    self.detection_classes = self.detection_graph.get_tensor_by_name('detection_classes:2')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3654, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3527, in _as_graph_element_locked
    len(op.outputs)))
KeyError: "The name 'detection_classes:2' refers to a Tensor which does not exist. The operation, 'detection_classes', exists but only has 1 outputs."
