### ISSUE TITLE
Running launch.sh and returning errors in logs

### ISSUE THREAD

**Issue by kaman86** [dataplayer12/homesecurity#17]
I have been installing and updating dependencies on my rasberry pi, when I run the project ($ ./launch.sh), I get the following messages in the log file. Can you please share ideas on how to resolve? Thanks in advance

`2020-11-28 20:46:43.196164: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "raspi3/securitycam.py", line 10, in <module>
    from file_manager import FileManagerThread, FileCleanerThread, counter

  File "/home/pi/projects/homesecurity/raspi3/file_manager.py", line 6, in <module>
    import human_detect as hd

  File "/home/pi/projects/homesecurity/raspi3/human_detect.py", line 62, in <module>
    odapi = DetectorAPI(path_to_ckpt=model_path)

  File "/home/pi/projects/homesecurity/raspi3/human_detect.py", line 18, in __init__
    serialized_graph = fid.read()

  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()

  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: ssd_mobilenet_v1_coco_2017_11_17/frozen_inference_graph.pb; No such file or directory`

**Comment by dataplayer12** [comment]
Hi, I have made a change which should fix this issue. Please do a `git pull` and try again. If the issue persists, let me know.

**Comment by kaman86** [comment]
Thanks for updating. Looks like one last error with missing directory, not sure why it is referencing a jetsontx2 file if i'm using the raspi3. 

```
2020-11-29 11:17:41.953018: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "jetsontx2/tx2_surveillance.py", line 12, in <module>
    import tensorflow.contrib.tensorrt as trt
ModuleNotFoundError: No module named 'tensorflow.contrib'

```

**Comment by dataplayer12** [comment]
In the launch.sh script, please change the DEVICE variable to raspi3 from jetsontx2

**Comment by kaman86** [comment]
Okay I did that, after I pulled it reset the device.

Now when I try, it shows activity in log file, received and email of alert,
had to grant access from my gmail account. I then reran launch.sh, and now
get out of resource and did not receive another email or motion detection.

**Comment by kaman86** [comment]
Okay working now. Had to enable access from google, as well as update firmware. Working like a charm now! Thank you

**Comment by dataplayer12** [comment]
Great that it works now. Good luck!
