### ISSUE TITLE
Tensorflow Model issue

### ISSUE THREAD

**Issue by JVTEAM** [dataplayer12/homesecurity#6]
Ran the launch bash, got this. 

 File "jetsontx2/tx2_surveillance.py", line 150, in <module>
    main()
  File "jetsontx2/tx2_surveillance.py", line 125, in main
    trt_graph = load_trt_pb(pb_path)
  File "/home/vondalej/homesecurity/jetsontx2/utils/od_utils.py", line 28, in load_trt_pb
    trt_graph_def.ParseFromString(pf.read())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: ./human_detection/ssd_mobilenet_v1_coco_trt.pb; No such file or directory
FATAL: exception not rethrown

 Noticed that there is another script to run to compile it.  When I ran that I got this...

Traceback (most recent call last):
  File "jetsontx2/compile_ssd_mobilenet.py", line 2, in <module>
    from tf_trt_models.detection import build_detection_graph
ModuleNotFoundError: No module named 'tf_trt_models'

**Comment by dataplayer12** [comment]
Hi, you need to install the `tf_trt_models` library from NVIDIA. The instructions are given [here](https://github.com/NVIDIA-AI-IOT/tf_trt_models). If I remember correctly, this used to come pre-installed with JetPack in one of the earlier releases, so I did not put this up as an extra dependency. Thank you for exposing this issue. I will update the setup instructions.

**Comment by JVTEAM** [comment]
I just "upgraded" to 4.4 and I'm having dependency issues like crazy.  Thanks for the pointers.

**Comment by JVTEAM** [comment]
Looks like common is one of your folders.  It's not picking it up right.

Traceback (most recent call last):
  File "jetsontx2/compile_ssd_mobilenet.py", line 4, in <module>
    from common.colors import cprint
ModuleNotFoundError: No module named 'common'

**Comment by dataplayer12** [comment]
This is probably related to the version of python you are using. Since the script is launched from project home directory and `common` directory has an `__init__.py` file, common should be picked up as a module. I have just checked that it works for python 3.7. Which version of python are you using?

**Comment by dataplayer12** [comment]
Also, please note that only python3 is supported.

**Comment by JVTEAM** [comment]
I'm using python3.6.

**Comment by JVTEAM** [comment]
well....I guess I'll just wait till I get the TX2 up and running because it's just not in the cards for the Nano today.  The mobilenet script keeps failing on me.

2020-07-15 10:40:40.450457: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:486] There are 1849 ops of 28 different types in the graph that are not converted to TensorRT: Fill, Merge, Switch, Range, ConcatV2, ZerosLike, Identity, NonMaxSuppressionV3, Squeeze, Mul, ExpandDims, Unpack, TopKV2, Cast, Transpose, Placeholder, Sub, Const, Greater, Shape, Where, Reshape, NoOp, GatherV2, AddV2, Pack, Minimum, StridedSlice, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
2020-07-15 10:40:41.872395: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:633] Number of TensorRT candidate segments: 2
2020-07-15 10:40:42.116825: F tensorflow/core/util/device_name_utils.cc:92] Check failed: IsJobName(job) 
Aborted (core dumped)

**Comment by dataplayer12** [comment]
This is surprising. As a workaround, please uncomment that line and add this line below it:
```python
cprint=print
```
The script should then run normally.

I don't understand why your tensorRT version does not recognize these ops. I have compiled this model with trt 4.x and 5.x without problems. Please share your tensorflow and tensorRT versions. I have found that sometimes builds fail on nano because of memory not being freed by processes which terminated unexpectedly. Restarting the nano should reset the memory and make enough of it available for your compilation to proceed successfully. For more discussion, please see #3

**Comment by JVTEAM** [comment]
tensorflow is 1.15.2.  TensorRT if I'm looking at it right is 7.1.3-1+cuda10.2

**Comment by dusty-nv** [comment]
You might want to check the fixes in these issues:

https://github.com/tensorflow/tensorrt/issues/197
https://github.com/tensorflow/tensorrt/issues/107

**Comment by dataplayer12** [comment]
@dusty-nv Thank you. I have updated the script with the fix suggested in tensorflow/tensorrt#197
@JVTEAM please confirm that this fixes the issue. I am not on 4.4, so can't verify immediately.

**Comment by dusty-nv** [comment]
It appears this may date back to TensorRT 6 / JetPack 4.3:   

https://jkjung-avt.github.io/jetpack-4.3/
(search for `Check failed: IsJobName(job)`)

So if you had test TRT 4 and TRT 5 but not TRT 6 or newer, that could make sense.

**Comment by JVTEAM** [comment]
That fixed it, thank you!
